In [1]:
# imports!
from datasets import load_dataset
import pandas as pd
import os

/home/kim/TDA_RI/TDA_reason-interpret/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# choose number of sentences
num_sen = 1600

In [3]:
## == HELLASWAG == ##

# import hellaswag
hellaswag_dataset = load_dataset("Rowan/hellaswag")
hellaswag_df = pd.DataFrame(hellaswag_dataset['test'][:num_sen])

# store
hellaswag_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/hellaswag.csv", index=False)

In [4]:
hellaswag_size = len(hellaswag_df)
print("Size is:", hellaswag_size)
hellaswag_df.head()

Size is: 1600

,ind,activity_label,ctx_a,ctx_b,ctx,endings,source_id,split,split_type,label
0,14,Wakeboarding,A man is being pulled on a water ski as he flo...,he,A man is being pulled on a water ski as he flo...,[mounts the water ski and tears through the wa...,activitynet~v_-5KAycAQlC4,test,indomain,
1,71,Javelin throw,A huge crowd is in the stands in an arena. A m...,several men,A huge crowd is in the stands in an arena. A m...,"[are water boarding in a river., are shown thr...",activitynet~v_-fjUWhSM6Hc,test,indomain,
2,73,Javelin throw,The man that threw the javelin celebrates. Ano...,several men,The man that threw the javelin celebrates. Ano...,"[run out to where the javelin lands again., th...",activitynet~v_-fjUWhSM6Hc,test,indomain,
3,76,Javelin throw,The second man to throw the javelin and a man ...,the same men,The second man to throw the javelin and a man ...,[do the same action but in different locations...,activitynet~v_-fjUWhSM6Hc,test,indomain,
4,78,Javelin throw,The same men run to the the javelin's landing ...,again,The same men run to the the javelin's landing ...,"[, another man does not throw his javelin., th...",activitynet~v_-fjUWhSM6Hc,test,indomain,

In [5]:
## == MMLU DATASETS == ##

# import mmlu_professional_law
mmlu_law_dataset = load_dataset("cais/mmlu", "professional_law")
mmlu_law_df = pd.DataFrame(mmlu_law_dataset['test'][:num_sen])

# store
mmlu_law_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_law.csv", index=False)


# import mmlu_moral_scenarios
mmlu_moral_dataset = load_dataset("cais/mmlu", "moral_scenarios")
mmlu_moral_df = pd.DataFrame(mmlu_moral_dataset['test'][:num_sen])

# store
mmlu_moral_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_moral.csv", index=False)


# import mmlu_professional_psychology
mmlu_psych_dataset = load_dataset("cais/mmlu", "professional_psychology")
mmlu_psych_df = pd.DataFrame(mmlu_psych_dataset['test'][:num_sen])

# store
mmlu_psych_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_psych.csv", index=False)


# import mmlu_elementary_mathematics
mmlu_math_dataset = load_dataset("cais/mmlu", "elementary_mathematics")
mmlu_math_df = pd.DataFrame(mmlu_math_dataset['test'][:num_sen])

# store
mmlu_math_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_math.csv", index=False)


# import mmlu_miscellaneous
mmlu_misc_dataset = load_dataset("cais/mmlu", "miscellaneous")
mmlu_misc_df = pd.DataFrame(mmlu_misc_dataset['test'][:num_sen])

# store
mmlu_misc_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_misc.csv", index=False)

In [9]:
mmlu_law_size = len(mmlu_law_df)
print("law size is:", mmlu_law_size)
mmlu_law_df.head()

law size is: 1534

,question,subject,choices,answer
0,"One afternoon, a pilot was flying a small airp...",professional_law,"[admissible, because the attorney-client privi...",2
1,"A state statute provides: ""Whenever a person k...",professional_law,"[not guilty, if the arrest was unlawful withou...",1
2,A taxpayer was notified by the government that...,professional_law,"[inadmissible, because it would violate the at...",3
3,A resident announced his candidacy for state r...,professional_law,[The resident's petition contained a large num...,2
4,A defendant was angry at his friend for marryi...,professional_law,[He intended to kill the friend and not the da...,1

In [10]:
mmlu_moral_size = len(mmlu_moral_df)
print("moral size is:", mmlu_moral_size)
mmlu_moral_df.head()

moral size is: 895

,question,subject,choices,answer
0,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",3
1,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",0
2,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",3
3,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",1
4,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",3

In [11]:
mmlu_psych_size = len(mmlu_psych_df)
print("psych size is:", mmlu_psych_size)
mmlu_psych_df.head()

psych size is: 612

,question,subject,choices,answer
0,Which of the following statements expresses a ...,professional_psychology,[Aging is related to an increase in vaginal lu...,3
1,"According to Piaget, children are ___________.",professional_psychology,"[“Blank slates”, Less intelligent than adults,...",2
2,If a test has a standard error of measurement ...,professional_psychology,[about 68% of the observed scores for the test...,1
3,Any substance that can have a negative impact ...,professional_psychology,"[An Apgar, A teratogen, Only a problem in the ...",1
4,If you were hired by a large company to develo...,professional_psychology,"[needs analysis., job evaluation., summative e...",0

In [12]:
mmlu_math_size = len(mmlu_math_df)
print("math size is:", mmlu_math_size)
mmlu_math_df.head()

math size is: 378

,question,subject,choices,answer
0,What is the value of p in 24 = 2p?,elementary_mathematics,"[p = 4, p = 8, p = 12, p = 24]",2
1,Ms. Perez drove a total of 40 miles in 5 days....,elementary_mathematics,"[5, 7, 8, 9]",2
2,Find the quotient of −40 ÷ (−8).,elementary_mathematics,"[1 over 5, −5, −1 over 5, 5]",3
3,A soccer team has $90.00 to buy soccer balls. ...,elementary_mathematics,"[4, 5, 6, 7]",1
4,You and three friends go to a concert. The tot...,elementary_mathematics,"[4t = 112; $448, 4t = 112; $28, t over 4 = 112...",1

In [13]:
mmlu_misc_size = len(mmlu_misc_df)
print("misc size is:", mmlu_misc_size)
mmlu_misc_df.head()

misc size is: 783

,question,subject,choices,answer
0,An important source of information on the cred...,miscellaneous,"[the Retail Merchants Association, the local c...",2
1,In preparation for a writing unit on short sto...,miscellaneous,"[Conferencing, Discipline-based inquiry, Self-...",1
2,Paper will burn at approximately what temperat...,miscellaneous,"[986 degrees, 2125 degrees, 3985 degrees, 451 ...",3
3,The Apple iMac computer is available in all of...,miscellaneous,"[Tangerine, Strawberry, Kiwi, Grape]",2
4,What were the first names of the early America...,miscellaneous,"[Morgan and Mason, Meriwether and William, Cab...",1