In [1]:
# imports!
from datasets import load_dataset
import pandas as pd
import os
import ast

In [2]:
# choose number of sentences
num_sen = 1000

# helper function
def make_zero_shot_prompt(row, dataset):
    if dataset == "hellaswag":
        question = row["ctx"].strip()
        choices = row["endings"]

    elif dataset == "mmlu":
        question = row["question"].strip()
        choices = row["choices"]

    labels = ["A", "B", "C", "D"]
    choices_text = "\n".join(f"{label}. {choice}" for label, choice in zip(labels, choices))

    return f"{question}\n{choices_text}\nAnswer:"

# add prompt used for testing
def no_shot_prompt(df, dataset):
    df["prompt"] = df.apply(
        lambda row: make_zero_shot_prompt(row, dataset),
        axis=1,
    )
    return df

In [3]:
## == HELLASWAG == ##

# import hellaswag
hellaswag_dataset = load_dataset("Rowan/hellaswag")
hellaswag_df = pd.DataFrame(hellaswag_dataset['validation']).sample(n=num_sen, random_state=8)

# store
hellaswag_df = no_shot_prompt(hellaswag_df, "hellaswag")
hellaswag_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/hellaswag.csv", index=False)

In [4]:
hellaswag_size = len(hellaswag_df)
print("Size is:", hellaswag_size)
hellaswag_df.head()

Size is: 1000

,ind,activity_label,ctx_a,ctx_b,ctx,endings,source_id,split,split_type,label,prompt
833,11435,River tubing,A group pose smiling for the camera. A group w...,the group,A group pose smiling for the camera. A group w...,"[gesture at the camera., meets in a field and ...",activitynet~v_GWRqx0obKzA,val,indomain,2,A group pose smiling for the camera. A group w...
173,2390,Running a marathon,A crowd watches as several runners in a race j...,they all,A crowd watches as several runners in a race j...,"[are interviewed by microphones outside., stop...",activitynet~v_SbY68ygmuEA,val,zeroshot,2,A crowd watches as several runners in a race j...
8586,39497,Home and Garden,[header] How to fix a loose toilet paper holde...,,[header] How to fix a loose toilet paper holde...,[[title] Remove the screw if possible by grasp...,wikihow~65014,val,indomain,0,[header] How to fix a loose toilet paper holde...
9624,47195,Personal Care and Style,[header] How to give a sensual massage [title]...,,[header] How to give a sensual massage [title]...,"[Put on lotion, wash your hands, and polish yo...",wikihow~77651,val,zeroshot,1,[header] How to give a sensual massage [title]...
5735,18560,Food and Entertaining,[header] How to train a blind dog [title] Exer...,,[header] How to train a blind dog [title] Exer...,[[substeps] Using a back or front clip harness...,wikihow~30578,val,indomain,0,[header] How to train a blind dog [title] Exer...

In [5]:
## == MMLU DATASETS == ##

# import mmlu_professional_law
mmlu_law_dataset = load_dataset("cais/mmlu", "professional_law")
mmlu_law_df = pd.DataFrame(mmlu_law_dataset['test']).sample(n=num_sen, random_state=8)
mmlu_law_df = pd.DataFrame(mmlu_law_dataset["test"]).reset_index(names="ind").sample(n=num_sen, random_state=8)

# store
mmlu_law_df = no_shot_prompt(mmlu_law_df, "mmlu")
mmlu_law_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_law.csv", index=False)


# import mmlu_moral_scenarios
mmlu_moral_dataset = load_dataset("cais/mmlu", "moral_scenarios")
mmlu_moral_df = pd.DataFrame(mmlu_moral_dataset['test']).reset_index(names="ind")

# store
mmlu_moral_df = no_shot_prompt(mmlu_moral_df, "mmlu")
mmlu_moral_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_moral.csv", index=False)


# import mmlu_professional_psychology
mmlu_psych_dataset = load_dataset("cais/mmlu", "professional_psychology")
mmlu_psych_df = pd.DataFrame(mmlu_psych_dataset['test']).reset_index(names="ind")

# store
mmlu_psych_df = no_shot_prompt(mmlu_psych_df, "mmlu")
mmlu_psych_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_psych.csv", index=False)


# import mmlu_elementary_mathematics
mmlu_math_dataset = load_dataset("cais/mmlu", "elementary_mathematics")
mmlu_math_df = pd.DataFrame(mmlu_math_dataset['test']).reset_index(names="ind")

# store
mmlu_math_df = no_shot_prompt(mmlu_math_df, "mmlu")
mmlu_math_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_math.csv", index=False)


# import mmlu_miscellaneous
mmlu_misc_dataset = load_dataset("cais/mmlu", "miscellaneous")
mmlu_misc_df = pd.DataFrame(mmlu_misc_dataset['test']).reset_index(names="ind")

# store
mmlu_misc_df = no_shot_prompt(mmlu_misc_df, "mmlu")
mmlu_misc_df.to_csv("~/TDA_RI/TDA_reason-interpret/datasets/mmlu_misc.csv", index=False)

In [6]:
mmlu_law_size = len(mmlu_law_df)
print("law size is:", mmlu_law_size)
mmlu_law_df.head()

law size is: 1000

,ind,question,subject,choices,answer,prompt
973,973,A department store had suffered a succession o...,professional_law,"[prevail, because she was detained for an unre...",0,A department store had suffered a succession o...
1087,1087,A police officer received a call from a friend...,professional_law,"[No, because the officer received enough facts...",1,A police officer received a call from a friend...
1332,1332,Four years ago the owner of a shopping center ...,professional_law,[The covenant in the pharmacist's lease can be...,0,Four years ago the owner of a shopping center ...
1076,1076,"A state education agency, following all statut...",professional_law,"[No, because the state also acquired fee simpl...",1,"A state education agency, following all statut..."
1152,1152,A property owner held title in fee simple to a...,professional_law,"[prevail, unless the person who was responsibl...",1,A property owner held title in fee simple to a...

In [7]:
mmlu_moral_size = len(mmlu_moral_df)
print("moral size is:", mmlu_moral_size)
mmlu_moral_df.head()

moral size is: 895

,ind,question,subject,choices,answer,prompt
0,0,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",3,For which of these two scenarios does the main...
1,1,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",0,For which of these two scenarios does the main...
2,2,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",3,For which of these two scenarios does the main...
3,3,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",1,For which of these two scenarios does the main...
4,4,For which of these two scenarios does the main...,moral_scenarios,"[Wrong, Wrong, Wrong, Not wrong, Not wrong, Wr...",3,For which of these two scenarios does the main...

In [8]:
mmlu_psych_size = len(mmlu_psych_df)
print("psych size is:", mmlu_psych_size)
mmlu_psych_df.head()

psych size is: 612

,ind,question,subject,choices,answer,prompt
0,0,Which of the following statements expresses a ...,professional_psychology,[Aging is related to an increase in vaginal lu...,3,Which of the following statements expresses a ...
1,1,"According to Piaget, children are ___________.",professional_psychology,"[“Blank slates”, Less intelligent than adults,...",2,"According to Piaget, children are ___________...."
2,2,If a test has a standard error of measurement ...,professional_psychology,[about 68% of the observed scores for the test...,1,If a test has a standard error of measurement ...
3,3,Any substance that can have a negative impact ...,professional_psychology,"[An Apgar, A teratogen, Only a problem in the ...",1,Any substance that can have a negative impact ...
4,4,If you were hired by a large company to develo...,professional_psychology,"[needs analysis., job evaluation., summative e...",0,If you were hired by a large company to develo...

In [9]:
mmlu_math_size = len(mmlu_math_df)
print("math size is:", mmlu_math_size)
mmlu_math_df.head()

math size is: 378

,ind,question,subject,choices,answer,prompt
0,0,What is the value of p in 24 = 2p?,elementary_mathematics,"[p = 4, p = 8, p = 12, p = 24]",2,What is the value of p in 24 = 2p?\nA. p = 4\n...
1,1,Ms. Perez drove a total of 40 miles in 5 days....,elementary_mathematics,"[5, 7, 8, 9]",2,Ms. Perez drove a total of 40 miles in 5 days....
2,2,Find the quotient of −40 ÷ (−8).,elementary_mathematics,"[1 over 5, −5, −1 over 5, 5]",3,Find the quotient of −40 ÷ (−8).\nA. 1 over 5\...
3,3,A soccer team has $90.00 to buy soccer balls. ...,elementary_mathematics,"[4, 5, 6, 7]",1,A soccer team has $90.00 to buy soccer balls. ...
4,4,You and three friends go to a concert. The tot...,elementary_mathematics,"[4t = 112; $448, 4t = 112; $28, t over 4 = 112...",1,You and three friends go to a concert. The tot...

In [10]:
mmlu_misc_size = len(mmlu_misc_df)
print("misc size is:", mmlu_misc_size)
mmlu_misc_df.head()

misc size is: 783

,ind,question,subject,choices,answer,prompt
0,0,An important source of information on the cred...,miscellaneous,"[the Retail Merchants Association, the local c...",2,An important source of information on the cred...
1,1,In preparation for a writing unit on short sto...,miscellaneous,"[Conferencing, Discipline-based inquiry, Self-...",1,In preparation for a writing unit on short sto...
2,2,Paper will burn at approximately what temperat...,miscellaneous,"[986 degrees, 2125 degrees, 3985 degrees, 451 ...",3,Paper will burn at approximately what temperat...
3,3,The Apple iMac computer is available in all of...,miscellaneous,"[Tangerine, Strawberry, Kiwi, Grape]",2,The Apple iMac computer is available in all of...
4,4,What were the first names of the early America...,miscellaneous,"[Morgan and Mason, Meriwether and William, Cab...",1,What were the first names of the early America...